savetobinary io module, issue #3
Veritomyx/PeakInvestigator-Python-SDK pull request #21
Opened 2019-02-13 22:06 UTC by jct197

Test script below to address issue#3:
```
from peakinvestigator.io import save_binary

headers = ['This is a header\n','it should contain meta data\n','There is no limit to number of lines, and is optional.\n']
data_points = [[1234.5,67.89],[1234.56,78.9],[1234.567,89.0]]
with open('Test.bin', 'wb') as file:
    save_binary(headers, data_points,handle=file)
```

2019-02-19 14:50 UTC, TDI-tenderholt requested changes
I left several comments that are essentially FYI.

For this PR, try out the Pythonic way using `with TemporaryFile() as file`. You should be able to accomplish the opening/closing/deleting temporary files in 2 lines instead of 8.

2019-02-19 14:50 UTC, TDI-tenderholt commented on tests/test_binary.py
> +            '# This is a header\n# it should contain meta data\n# There is no limit to number of lines, and is optional.\n$x\x9cc`\x00\x03f\x87\xc9^`\x86C\xc0\x8f\xaf\x87\xfac4\x81|\xdb\x82\xc5\xd7\x
Why are the byte-strings in a list?

2019-02-19 14:50 UTC, TDI-tenderholt commented on tests/test_binary.py
> +        fd, filename = tempfile.mkstemp()
Is there a reason you went with `mkstemp` here and below? `tempfile` also has `TemporaryFile` that is auto-deleted at the end, which seems like a cleaner solution (i.e. less code!).

2019-02-19 14:50 UTC, TDI-tenderholt commented on tests/test_binary.py
> +            save_binary(headers, data_points, handle=file)
Note that the file descriptors (`fd` and `fd2`) returned from `mkstemp` are already open, so these subsequent calls to `open` aren't really necessary.

2019-02-19 14:50 UTC, TDI-tenderholt commented on tests/test_binary.py
> +        fd, filename = tempfile.mkstemp()
I think the Pythonic way to use `TemporaryFile` is something like:

```
with tempfile.TemporaryFile() as file:
  save_binary(...)
```

2019-02-19 14:50 UTC, TDI-tenderholt commented on tests/test_binary.py
> +        os.close(fd)
I think you're supposed to do `fd.close()` instead of `os.close(fd)`.

2019-02-19 14:51 UTC, TDI-tenderholt commented on tests/test_binary.py
> +            '# This is a header\n# it should contain meta data\n# There is no limit to number of lines, and is optional.\n$x\x9cc`\x00\x03f\x87\xc9^`\x86C\xc0\x8f\xaf\x87\xfac4\x81|\xdb\x82\xc5\xd7\x
Also, why don't use use these in the actual tests?

2019-02-19 14:52 UTC, TDI-tenderholt commented on tests/test_binary.py
> +            '# This is a header\n# it should contain meta data\n# There is no limit to number of lines, and is optional.\n$x\x9cc`\x00\x03f\x87\xc9^`\x86C\xc0\x8f\xaf\x87\xfac4\x81|\xdb\x82\xc5\xd7\x
Scratch that, you do. But you also create duplicated variables. I'll comment there.

2019-02-20 16:05 UTC, jct197 commented
Comments are addressed in latest commit.

2019-02-20 16:59 UTC, TDI-tenderholt approved these changes

2019-02-20 17:02 UTC, TDI-tenderholt commented
One last thing: is the test actually run via Travis? I didn't see a change in the associated script.

2019-02-20 17:21 UTC, jct197 commented
Travis tests passed on updated test_binary.py.
https://github.com/Veritomyx/PeakInvestigator-Python-SDK/pull/21/commits/4ee21a9853777a8d1f6f60f89878988ab523561c

2019-02-20 17:46 UTC, TDI-tenderholt commented
But you haven't made any changes so that Travis automatically runs the `test_binary.py` file: https://github.com/jct197/PeakInvestigator-Python-SDK/blob/binaryiomodule/travis/run_travis_tests.sh

2019-02-20 18:05 UTC, jct197 commented
Updated file looks to have passed this morning.
Should I make a new PR for verification?
![image](https://user-images.githubusercontent.com/13668757/53113687-03fd2900-34f7-11e9-8a16-a558ac40d7b2.png)

2019-02-20 18:14 UTC, merged